version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - caddy

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
